config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :recipes
  resources :ingredients, except: [:show]
  resources :ferms
  resources :hops
  resources :yeasts

  # The following is how you route to share controllers/views
  # Note: You'll need separate folder and partial for each 'type' regardless
  #resources :ferms, controller: 'ingredients', type: 'ferm'
  #resources :hops, controller: 'ingredients', type: 'hop'
  #resources :yeasts, controller: 'ingredients', type: 'yeast'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>On Draft - About Page</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>On Draft - Contact Page</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>On Draft - Help Page</h1>

app/views/static_pages/home.html.erb
<div class="center">
  <h1>On Draft - Home Page</h1>
  <% if !logged_in? %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <p>Already a member? <%= link_to "Log in", login_path %></p>
  <% end -%>

</div>